module CountryGuesser
  LANGUAGE_TO_COUNTRY = {
    "nn"=>["NO"],
    "uk"=>["UA"],
    "it"=>["IT", "GI", "CH", "LY", "SM"],
    "zh_TW"=>["TT", "VN", "HK"],
    "no"=>["NO"],
    "st"=>["ZA"],
    "tk"=>["TM"],
    "bn"=>["IN"],
    "mn"=>["MN"],
    "ja"=>["JP"],
    "fr"=>["FR", "CD", "GG", "RW", "CG", "LU", "TT", "CH", "CI", "JE", "SC",
      "VN", "BE", "MU", "DJ", "BI", "CA"],
    "hi"=>["TT", "AE", "IN"],
    "de"=>["DE", "LU", "CH", "LI", "AT", "BE", "RO"],
    "ne"=>["NP"], "jw"=>["ID"],
    "ta"=>["IN", "SG"],
    "tl"=>["PH"],
    "pt_PT"=>["PT", "GI"],
    "hu"=>["HU", "SK", "RO"],
    "sk"=>["SK"],
    "fi"=>["FI"],
    "sv"=>["SE", "FI"],
    "iw"=>["IL"],
    "az"=>["AZ"],
    "zh"=>["TW"],
    "ru"=>["RU", "KZ", "KG", "AZ", "LV", "UA", "TM", "AM", "UZ"],
    "ky"=>["KG"],
    "es"=>["ES", "HN", "CU", "PR", "TT", "PA", "VE", "DO", "BO", "GI", "PE",
      "PY", "NI", "CL", "SV", "CO", "UY", "BZ", "CR", "EC", "GT", "AR", "MX"],
    "ko"=>["KR"],
    "pt_BR"=>["BR"],
    "sw"=>["RW", "KE"],
    "ga"=>["IE"],
    "id"=>["ID"],
    "eu"=>["ES"],
    "gl"=>["ES"],
    "xh"=>["ZA"],
    "uz"=>["TM", "UZ"],
    "mr"=>["IN"],
    "fa"=>["AE"],
    "zu"=>["LS", "ZA"],
    "af"=>["NA", "ZA"],
    "pl"=>["PL"],
    "hy"=>["AM"],
    "pa"=>["PK"],
    "te"=>["IN"],
    "ar"=>["AE", "LY", "SA", "DJ"],
    "ms"=>["MY", "SG"],
    "el"=>["GR"],
    "ro"=>["RO"],
    "mt"=>["MT"],
    "ur"=>["AE", "PK"],
    "da"=>["DK", "GL"],
    "ca"=>["ES"],
    "tr"=>["TR"],
    "zh_CN"=>["SG"],
    "nl"=>["NL", "BE", "ID"],
    "vi"=>["VN"],
    "lt"=>["LT", "LV"],
    "th"=>["TH"],
    "fo"=>["DK"],
    "en"=>["US", "AS", "IE", "NP", "MY", "UK", "FM", "VC", "PR", "TT", "AU",
      "PA", "NA", "GG", "LS", "RW", "VG", "AE", "GI", "VI", "AG", "TH", "CH",
      "NF", "JE", "AI", "GL", "PH", "CK", "GM", "LY", "IN", "NZ", "NI", "SC",
      "PK", "VN", "MS", "TO", "MT", "BE", "PN", "MU", "UG", "SG", "ZA", "BZ",
      "SH", "MW", "FJ", "CR", "HK", "JM", "KE", "CA", "ID"],
    "lv"=>["LV"]
  }.freeze
  
module_function
  def countries_from_language(language)
    LANGUAGE_TO_COUNTRY[language]
  end

  def country_from_language(language)
    (countries_from_language(language) || []).first
  end
end
